In [ ]:
import pandas as pd

In [2]:
df=pd.read_csv('wines_SPA.csv')

In [3]:
df.head()

winery           wine  year  rating  num_reviews country  \
0  Teso La Monja          Tinto  2013     4.9           58  Espana   
1         Artadi  Vina El Pison  2018     4.9           31  Espana   
2   Vega Sicilia          Unico  2009     4.8         1793  Espana   
3   Vega Sicilia          Unico  1999     4.8         1705  Espana   
4   Vega Sicilia          Unico  1996     4.8         1309  Espana   

             region   price                  type  body  acidity  
0              Toro  995.00              Toro Red   5.0      3.0  
1    Vino de Espana  313.50           Tempranillo   4.0      2.0  
2  Ribera del Duero  324.95  Ribera Del Duero Red   5.0      3.0  
3  Ribera del Duero  692.96  Ribera Del Duero Red   5.0      3.0  
4  Ribera del Duero  778.06  Ribera Del Duero Red   5.0      3.0

In [4]:
df.shape

(7500, 11)

In [5]:
import numpy as np
np.unique(df.acidity)

array([ 1.,  2.,  3., nan])

In [6]:
set(df['type'])

{'Albarino',
 'Cabernet Sauvignon',
 'Cava',
 'Chardonnay',
 'Grenache',
 'Mencia',
 'Monastrell',
 'Montsant Red',
 'Pedro Ximenez',
 'Priorat Red',
 'Red',
 'Ribera Del Duero Red',
 'Rioja Red',
 'Rioja White',
 'Sauvignon Blanc',
 'Sherry',
 'Sparkling',
 'Syrah',
 'Tempranillo',
 'Toro Red',
 'Verdejo',
 nan}

In [8]:
from sklearn.preprocessing import OneHotEncoder

# Sample data (categorical features)
# data = ['red', 'green', 'blue', 'red', 'green']
data=df.type

# Create a OneHotEncoder object
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')

# Fit the encoder to the data (learns the categories)
encoder.fit(data[:, np.newaxis])

# Transform the data into one-hot encoded format
encoded_data = encoder.transform(data[:, np.newaxis])

# Print the original data and encoded data
print("Original data:", data)
print("One-hot encoded data:", encoded_data)


Original data: 0                   Toro Red
1                Tempranillo
2       Ribera Del Duero Red
3       Ribera Del Duero Red
4       Ribera Del Duero Red
                ...         
7495               Rioja Red
7496             Priorat Red
7497                     Red
7498    Ribera Del Duero Red
7499    Ribera Del Duero Red
Name: type, Length: 7500, dtype: object
One-hot encoded data: [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


<ipython-input-8-977eee3abff9>:11: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  encoder.fit(data[:, np.newaxis])
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
<ipython-input-8-977eee3abff9>:14: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  encoded_data = encoder.transform(data[:, np.newaxis])


In [9]:
data

0                   Toro Red
1                Tempranillo
2       Ribera Del Duero Red
3       Ribera Del Duero Red
4       Ribera Del Duero Red
                ...         
7495               Rioja Red
7496             Priorat Red
7497                     Red
7498    Ribera Del Duero Red
7499    Ribera Del Duero Red
Name: type, Length: 7500, dtype: object

In [10]:
encoded_data

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
type1=[]
for i in (encoded_data):
  indices = np.where(i == 1)[0]
  type1=np.append(type1,indices)

In [12]:
df_=df
df_['type1']=type1

In [13]:
df_.head()

winery           wine  year  rating  num_reviews country  \
0  Teso La Monja          Tinto  2013     4.9           58  Espana   
1         Artadi  Vina El Pison  2018     4.9           31  Espana   
2   Vega Sicilia          Unico  2009     4.8         1793  Espana   
3   Vega Sicilia          Unico  1999     4.8         1705  Espana   
4   Vega Sicilia          Unico  1996     4.8         1309  Espana   

             region   price                  type  body  acidity  type1  
0              Toro  995.00              Toro Red   5.0      3.0   19.0  
1    Vino de Espana  313.50           Tempranillo   4.0      2.0   18.0  
2  Ribera del Duero  324.95  Ribera Del Duero Red   5.0      3.0   11.0  
3  Ribera del Duero  692.96  Ribera Del Duero Red   5.0      3.0   11.0  
4  Ribera del Duero  778.06  Ribera Del Duero Red   5.0      3.0   11.0

In [15]:
df.body.isnull().sum()

1169

In [16]:
df_.body.fillna(0, inplace=True)

In [17]:
df_.acidity.isnull().sum()

1169

In [18]:
df_.acidity.fillna(df.acidity.mean(),inplace=True)

In [19]:
np.unique(df_.type1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21.])

In [20]:
df_.type1.isnull().sum()

0

In [21]:
df_.price.isnull().sum()

0

In [22]:
x=df_[['rating','num_reviews','body','acidity','price']]
y=df_[['type1']]

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

clf.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/pytho